name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Test
        run: |
          cargo build --verbose
          cargo test --verbose

      - name: Run inputs.sh in a container
        run: |
          docker run --rm -v $(pwd):/app -w /app <container_image> bash ./inputs.sh > output.txt
          cat output.txt
    # - name: Build
    #   run: cargo build --verbose